name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install Expo CLI
    - name: Install Expo CLI
      run: npm install --global expo-cli eas-cli

    # Install project dependencies
    - name: Install dependencies
      run: npm install --force

    # Setup EAS
    - name: 🏗 Setup EAS
      uses: expo/expo-github-action@v8
      with:
          eas-version: latest
          token: ${{ secrets.EXP0_TOKEN }}

    # Check who is logged in
    - name: Review Username
      run: eas whoami

    # Build the Android APK
    - name: Build Android APK
      run: eas build --platform android --profile production --non-interactive

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: dist/*.apk
