name: Build Android APK Gradle

on:
    workflow_dispatch:
    release:
      types:
        - created

jobs:
  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java (Gradle requires Java)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Set up Node.js (React Native requires Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install
        npm install -g react-native-cli

    # Set up environment variables for Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools: '31.0.0'
        target: 'android-31'

    # Build the APK
    - name: Build APK
      working-directory: android
      run: ./gradlew assembleRelease

    # Upload the APK as a workflow artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
