name: Build Android APK

on:
  workflow_dispatch:
  release:
    types:
      - created
  
jobs:
  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install Expo CLI
    - name: Install Expo CLI
      run: npx install --global expo-cli eas-cli --force

    # Login to Expo
    - name: Login to Expo
      run: eas login --token ${{ secrets.EXP0_TOKEN }}

    # Install project dependencies
    - name: Install dependencies
      run: npm install

    # Build the Android APK
    - name: Build Android APK
      run: eas build --platform android --profile production --non-interactive

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: dist/*.apk
