name: Build and Test for Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run unit tests
      - name: Run unit tests
        run: npx jest

      # Set up Expo for building binaries
      - name: Set up Expo
        run: npx expo install

      # Build the Android binary
      - name: Build Android APK
        run: |
          npx expo build:android --type apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build the iOS binary
      - name: Build iOS IPA
        run: |
          npx expo build:ios --type archive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Upload artifacts
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: dist/*.apk

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: dist/*.ipa

  notify:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Notify and provide links to the release and artifacts
      - name: Notify Jeremy
        run: |
          echo "Release complete! Here are your links:"
          echo "GitHub Release Page: ${{ github.event.release.html_url }}"
          echo "Android APK: <link-to-apk>"
          echo "iOS IPA: <link-to-ipa>"
