name: Build and Test on Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --force

      - name: Run unit tests
        run: npm test

  build:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods dependencies (iOS only)
        run: cd ios && pod install

      - name: Build Android binary
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Upload Android artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Build iOS binary
        run: |
          cd ios
          xcodebuild -workspace Volunteam.xcworkspace \
                     -scheme Volunteam \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/Volunteam.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Volunteam.xcarchive \
                     -exportPath $PWD/build \
                     -exportOptionsPlist ExportOptions.plist
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-release.ipa
          path: ios/build/Volunteam.ipa
